### ISSUE TITLE
calculate local gyrification index

### ISSUE THREAD

**Issue by mattcieslak** [PennLINC/freesurfer_tabulate#1]

**Comment by LenaDorfschmidt** [comment]
mris_compute_lgi -i lh.pial
mris_compute_lgi -i rh.pial

**Comment by mattcieslak** [comment]
We're getting lGI in:

 - mgh files in fsaverage (also smoothed with the qcache kernels)
 - cifti files in fsLR (plus the smoothed versions)
 - Region summaries (even though it's not the gold standard)
 - the pial_lgi files are included in the freesurfer.tar.xz archive as well
