### ISSUE TITLE
Redundant vertex count and area measures in surfstats.tsv

### ISSUE THREAD

**Issue by valeriejill** [PennLINC/freesurfer_tabulate#4]
In the surfstats.tsv, seems like NumVert, NVertices_gwpct, NVertices_piallgi are redundant and SurfArea, Area_mm2_gwpct, Area_mm2_piallgi are redundant. Keep as sanity check or remove?

**Comment by mattcieslak** [comment]
How about doing the sanity check in the code while gathering all this data? If NVertices and Area aren't consistent, raise an error and stop the process before writing out the results. Then end users won't have to perform this sanity check themselves and it will stop erroneous data at the source

**Comment by valeriejill** [comment]
That's a great idea! 
I think they'll have to be rounded to the nearest whole number as we discovered yesterday.
